### PR TITLE
PR for discussion

### PR DESCRIPTION
**Pull request by philwebb**
The following PR contains my best attempt to fix a number of recently raised issues. It needs a CSS expert to review if they are correct or not.

### CODE REVIEW

**Comment by bclozel** [comment]
Why were the dark theme variants added back? There were removed on purpose in #40

**Comment by philwebb** [comment]
Totally unintentional. I probably included them accidentally when upgrading highlight.js.

**Comment by brenuart** [comment]
@philwebb Your commit mentions an upgrade to Highlight.js `10.3.0` but the version you included is `10.2.0` - at least this is what the comment in `hightlight.js` says...
Maybe this comment is wrong or their download mechanism has a problem. IMHO you'd better double check what version you actually included ;-)

**Comment by philwebb** [comment]
That's interesting. I went to https://highlightjs.org/ and clicked the "Get version 10.3.0" then the "download" button but indeed the actual file states `10.2.0`. I guess the download button is wrong and the actual release version is 10.2.0.

**Comment by oodamien** [comment]
> Don't use display:block for tableblocks

Issue with table:

image

**Comment by oodamien** [comment]
> Consider different tab style

Not fan of this style (prefer the old one which follow the design guideline).

**Comment by philwebb** [comment]
> Issue with table:

I've no idea how to fix this one then. I tried to look at a classic asciidoctor page to work out why short tables looked bad with the new css and this was all I could find.

You can see an example [here](https://docs.spring.io/spring-boot/docs/2.4.0-SNAPSHOT/reference/htmlsingle/#getting-started-system-requirements-servlet-containers).

> Not fan of this style (prefer the old one which follow the design guideline).

I like the existing style in small doses, but we've added a lot of new tabs the latest version of the Boot docs. You can see an example [here](https://docs.spring.io/spring-boot/docs/2.4.0-SNAPSHOT/reference/htmlsingle/#boot-features-spring-mvc-pathmatch). I started to find them a bit to be a bit distracting from the content which is why I started to experiment. Perhaps there's something else that can be done to tone them down a bit?

**Comment by brenuart** [comment]
> Issue with table:

I'm not a CSS expert at all, but here is what we added to temporarily fix the issue:
```
table.tableblock {
  display: table;
}
```
Not saying this is the root cause of the issue... but at least it seems to have solved the issue on our side.

**Comment by bclozel** [comment]
I've cherry-picked a few changes from this PR and added more, fixing #48 #53 #55 and #56.
I'm keeping this PR opened for now as the changes proposed here are likely to cause regressions, but we'd like to solve those problems still!

We first need to add multiple known edge cases to our test document in `src/test/resources/index.adoc` so as to validate fixes there. As @oodamien said, many components are reusing `<table>` tags in asciidoctor and fixing one issue might cause unwanted changes.

**Comment by philwebb** [comment]
I've opened other PRs for some of the remaining issues. I'll close this one so we can discuss things on the individual PRs.

**Pull request closed without merging**
